name: Build project and check quality

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Unit tests
        run: mvn -B test --file pom.xml
